import os
from pathlib import Path


class Context:
    """
    Takes a (temporary) directory and creates a bunch of subdirectories for use by the packagers.
    There should be one build directory per packaging process
    """

    def __init__(self, directory: str | os.PathLike):
        directory = Path(directory)

        def makedir(path: Path):
            os.makedirs(str(path), exist_ok=True)
            return path

        self.base_dir = makedir(directory)

        # may be used to store temporary data during the package build process
        self.work_dir = makedir(directory / "build")

        # install prefix mapping to / when installed
        self.install_root_dir = makedir(directory / "install-root")

        # all artifacts generated by the packager should end up in this directory, where they will be collected and
        # moved to a user-specified directory
        self.out_dir = makedir(directory / "out")
